urls=(
    "https://www.youtube.com/embed/R7vrbiDi0Tc?autoplay=1&rel=0&modestbranding=1"
    "https://orf.at"
    "http://corndog.io/"
    "https://topfdeckel.at/tageskarte"
    "https://www.bbc.com/weather/2761369"
    "https://metalab.at"
    "https://www.window-swap.com/Window"
    "https://puginarug.com/"
)